# Generated by Django 5.1.2 on 2024-11-03 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_usbdevice_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalrequest',
            name='approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL, verbose_name='承認者'),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='rental_period',
            field=models.PositiveIntegerField(null=True, verbose_name='レンタル期間（日数）'),
        ),
        migrations.CreateModel(
            name='UserPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='PCの製品番号')),
                ('antivirus_version', models.CharField(max_length=50, verbose_name='ウイルス対策のバージョン')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='pc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.userpc', verbose_name='利用PC'),
        ),
    ]
