# Generated by Django 5.1.2 on 2024-11-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rentalrequest_approver_rentalrequest_rental_period_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalrequest',
            name='rental_period',
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='end_date',
            field=models.DateField(null=True, verbose_name='返却日'),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='start_date',
            field=models.DateField(null=True, verbose_name='レンタル開始日'),
        ),
    ]
