# Generated by Django 5.1.2 on 2024-11-04 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_rentalrequest_rental_period_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='メーカー名')),
            ],
        ),
        migrations.AddField(
            model_name='usbdevice',
            name='capacity',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='容量（バイト数）'),
        ),
        migrations.AddField(
            model_name='usbdevice',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='購入日'),
        ),
        migrations.AddField(
            model_name='usbdevice',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.manufacturer', verbose_name='メーカー'),
        ),
    ]
