# Generated by Django 5.1.2 on 2024-11-04 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_manufacturer_usbdevice_capacity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturerWhitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.manufacturer', verbose_name='メーカー')),
            ],
        ),
    ]
