# Generated by Django 5.1.2 on 2024-11-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_manufacturerwhitelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalrequest',
            name='is_returned',
            field=models.BooleanField(default=False, verbose_name='返却済み'),
        ),
    ]
